language: ruby
notifications:
  email: false
  slack:
    secure: Bun3OrKUE/Ob6eqR8qS5+zUrxPM9WGT/2BHRqKlOwy8nSiQkcViFdtsH6bToVoG/+F7EAiW+jiwtEUE9xV4mklX0Fy3wYkQA43PUZ6dPJ8YtOgVf5AuE9Z5r123C856skLSYhrGc8ZRRY7QmbZNRXzptuS1vVJDAL+MI3TFmnraTBNX0s2QWEzFAcNiubtJyyDhiGRJAW/6+bmcHudEZy+xrmfL2khwxUUDmkfx2L6fyRZUdZT8cy/Umz9sjqWM7Q2SnQkF2nOFnXmhcAAXgo7hcHMK6FljsV4Y/uIYDoCS0Kp2WrW/+KwZOjUkjwgTMCNV+ckzCgA+HLxvbej879t5/kmA+3A7iYB8ZJ6c17m8R9w7cZEpAe7wtDfTYlm0Ztc0C50sWkPXbYNHzR4Scrjt9864Cucyi95cDETVyEkjwxs7Tbv5xAlfCsAxyxGMlQdO/ntvGQMlKeRKwsh8InbOOM/UQg7uYKbQFM4k/gQbPT023g8GIZBPoawCUxOHxpw2jlOyv0WnoZ/jwHHLC7l1iXk8wZU9uLghr6rlK7WCM0JfImYylIA0qhDbAFot3cICpNYLdt2MD1zXpiw3qIwrJ+PKmg4g10ju9DhsQG0RZF/wW1Tdu+DcgX2MMfwHAS8XJO/sTAZ/yOr2Z2lLd+iU64eSuU9Zv+CxAAhim7UU=
rvm:
- 2.3.0
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rake ci:tests
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: Ug0x11gIJ0s6/27IfMpolFyOpo7gn2FuyfS52o2VgymeLsJicbrt3Uz0QEHiWZozjjFcyXQ0YHYsmwDwZAhHP8UkjHMb0RSrpgTxAZpPABVVqh4wZ/xZhu91DtI2Aa86P4XOm7kSO7X6yV1HwWXdpKIctt1rFO6OEA9tF26N3I8MznNFfZ2YQ8yiFwS6rjfL0q9qWfZ9v1+trZKFwRviXkARKsUlpwdVl+p095ChfXoDTvfsP+9ClL5rdGt7E3b3U0DV1DAU1vvlFZwSSUUy6PYUHfZ3IFUfEwIQMnNFy0o5x/fZ2mP8zIp0jDd9CJ2wGcvF3YQlRoexbQ8IvXi6E0tbgY9R38XuExP1K49AYn4E+5S5zvf2+nP/Z2Iw7w0kwQjQBWL3gN8mwwIfBnXNCzo40kzhnqFf1NPNTGYVUTR/9CCuj/FAA6TtLDESo9DUe3v22BPuZErR9EFhZXprfA6OtLc0pnJIlTzBio9ys+GadAr5EqUbKnLvLu1t1pR+pFhD1VeD2P1hQdc7li4esHjbcjuQHwMCxo7fn4pLh4dcJVyIWTtOfXPscwLZh7y6QKue9LMJRXhIdxafWu2Xt4QUk+tENTzkyEayTeumC93MZJ/zzxghnUZtIP0hBi8Jhr8qZoH4TO107wghxQMSJOg3evOdE5BqkpPU2pLYS/c=
  app:
    develop: slow-food-august
    master: best-slow-food
  on:
    repo: CraftAcademy/sf-online-august
